site_dev:
  target: dev
  outputs:
    dev:
      type: mysql
      host: 195.154.196.76
      port: 13498
      user: site_dev
      password: "87]N_8J!IlO+Y?(DB'B$"
      schema: site_dev
      database: site_dev
      threads: 1  # Add this if you plan to run multiple threads